- name: install tools
  yum: name="@Development tools" state=present
  tags: kafka

- name: create group
  group:
    name: kafka
    state: present
  tags: kafka

- name: create user
  user:
    name: kafka
    group: kafka
  tags: kafka

- name: Setting internal variable
  set_fact:
    kafka_name: kafka_{{ kafka.scala_version }}-{{ kafka.version }}
  tags: kafka

- name: Setting internal variable
  set_fact:
    kafka_dir: "{{ kafka.install_dir }}/{{ kafka_name }}"
  tags: kafka

- name: check if tar has been downloaded
  command: test -f /tmp/{{ kafka_name }}.tgz
  register: kafka_tar_downloaded
  failed_when: kafka_tar_downloaded.rc not in [0, 1]
  changed_when: False
  tags: kafka

- name: Ensure Kafka tar is downloaded
  get_url:
    url: "{{ kafka.mirror }}/kafka/{{ kafka.version }}/{{ kafka_name }}.tgz"
    dest: /tmp
  tags: kafka
  when: kafka_tar_downloaded.rc == 1

#- name: Ensure tar is extracted
#  command: tar xzf /tmp/{{ kafka_name }}.tgz chdir="{{ kafka.install_dir }}"
#  tags: kafka

- name: Ensures data dir {{ kafka.install_dir }} exists
  file:
    path: "{{ kafka.install_dir }}"
    state: directory
    owner: kafka
    group: kafka
  tags: kafka

- name: Ensure tar is extracted
  unarchive:
    copy: no
    src: "/tmp/{{ kafka_name }}.tgz"
    dest: "{{ kafka.install_dir }}"
    owner: kafka
    group: kafka
  tags: kafka

# Config and start Kafka
- name: Ensures data dir {{ kafka.data_dir }} exists
  file:
    path: "{{ kafka.data_dir }}"
    state: directory
    owner: kafka
    group: kafka
  tags: kafka

- name: Copy real config
  template:
    src: server.properties
    dest: "{{ kafka_dir }}/config/real-server.properties"
  notify: restart kafka
  tags: kafka

# Kafka Log
- name: Ensures log dir {{ kafka.log_dir }} exists
  file:
    path: "{{ kafka.log_dir }}"
    state: directory
    owner: kafka
    group: kafka
  tags: kafka

#- name: force restart kafka
#  shell: cd {{ kafka_dir }}; bin/kafka-server-stop.sh; sleep 15; rm {{ kafka.data_dir }}/.lock; nohup bin/kafka-server-start.sh config/real-server.properties > /home/vagrant/kafka.log 2>&1 &

- name: systemd start script
  template:
    src: kafka-systemd.j2
    dest: /etc/systemd/system/kafka.service
    owner: root
    group: root
    mode: 644
  notify: start kafka
  tags: kafka
